image:
  file: .gitpod.Dockerfile

ports:
  - port: 1313
    onOpen: open-preview

tasks:
  - before: git pull --recurse-submodules
    init: hugo server --baseUrl $(gp url 1313) --appendPort=false --disableFastRender --buildDrafts --buildFuture
