image:
  file: .gitpod.Dockerfile

ports:
  - port: 1313
    onOpen: open-preview

tasks:
  - init: Start Hugo server 
    command: git pull --recurse-submodules
    command: hugo server --baseUrl $(gp url 1313) --appendPort=false --disableFastRender --buildDrafts --buildFuture
