# https://gohugo.io/getting-started/configuration/
# https://gohugo.io/getting-started/configuration-markup/

module:
  imports:
    - path: github.com/luizdepra/hugo-coder

ignoreFiles:
  - README\.md$

baseurl: https://philoserf.com
title: philoserf

params:
  author: Mark Ayers
  avatarurl: /assets/avatar.jpg
  description: The journal of a philosopher serf
  info: A human being, being human
  keywords: "blog,developer,personal"
  favicon_16: /assets/favicon-16x16.png
  favicon_32: /assets/favicon-32x32.png
  footercontent: That is all. Nothing more to see here. Move along.
  hideCopyright: false
  hideCredits: false
  hideFooter: false
  since: 2016
  commit: "https://github.com/philoserf/philoserf.com/tree/"
  enableTwemoji: true
  colorScheme: auto
  hidecolorschemetoggle: false
  utterances:
    repo: philoserf/comments
    label: utterances
    issue-term: pathname
    theme: icy-dark
  social:
    - icon: fa fa-github fa-2x
      name: GitHub
      url: "https://github.com/philoserf/"
      weight: 1
    - icon: fa fa-twitter fa-2x
      name: Twitter
      url: "https://twitter.com/philoserf/"
      weight: 2
    - icon: fa fa-linkedin fa-2x
      name: LinkedIn
      url: "https://linkedin.com/in/markpaulayers/"
      weight: 2

taxonomies:
  category: topics
  tag: tags
  series: series

menu:
  main:
    - name: Now
      url: now/
      weight: 1
    - name: The rules
      url: the_rules/
      weight: 2
    - name: Articles
      url: posts/
      weight: 3
    - name: Kit
      url: kit/
      weight: 4
    - name: About
      url: about/
      weight: 5
    - name: Contact
      url: contact/
      weight: 6

defaultcontentlanguage: en
languagecode: en
paginate: 20
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
pygmentsstyle: bw
